### PR TITLE
[feat] Adds exp graph to dash

### PR DESCRIPTION
**Pull request by tgreenhalgh**

### CODE REVIEW

**Comment by femi-saliu** [comment]
It might be smart to factor this code into a factory that we can just inject into default and expenseController
So that we dont need to have the same functions declared twice

**Comment by tgreenhalgh** [comment]
Yeah, crossed my mind. We'd need a couple flags for the graph title and
legend. Should I work on that now?

**Comment by femi-saliu** [comment]
What do you mean by flags?

**Comment by tgreenhalgh** [comment]
so when call the function, we can pass a title (not a flag, sorry) and these two are flags: 
dataLabels: { enabled: false}, showInLegend: true

**Comment by femi-saliu** [comment]
ok sounds good, I want to start working on splitting expenses today and I have an implementation plan but Ill hold off until you have the factory done. Contact me if you need any help.

**Pull request merged**
